runtime: nodejs20
env: standard
instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.95
  min_instances: 1
  max_instances: 1

# Environment variables
# includes:
#   - env.yaml

# Get Environment Variable from GitHub Secrets
env_variables:
  PORT: ${{ secrets.PORT }}
  DEFAULT_IMAGE: ${{ secrets.DEFAULT_IMAGE }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DIRECT_URL: ${{ secrets.DIRECT_URL }}
  JWT_AT_SECRET: ${{ secrets.JWT_AT_SECRET }}
  JWT_RT_SECRET: ${{ secrets.JWT_RT_SECRET }}
  JWT_AT_EXPIRE: ${{ secrets.JWT_AT_EXPIRE }}
  JWT_RT_EXPIRE: ${{ secrets.JWT_RT_EXPIRE }}
  REDIS_HOST: ${{ secrets.REDIS_HOST }}
  REDIS_PORT: ${{ secrets.REDIS_PORT }}
  REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
  MAIL_HOST: ${{ secrets.MAIL_HOST }}
  MAIL_PORT: ${{ secrets.MAIL_PORT }}
  MAIL_SECURE: ${{ secrets.MAIL_SECURE }}
  MAIL_USER: ${{ secrets.MAIL_USER }}
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
  MAIL_FROM: ${{ secrets.MAIL_FROM }}
  MAIL_NAME: ${{ secrets.MAIL_NAME }}
  CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
  CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
  CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

# Basic handlers
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

# Minimize resource usage
inbound_services:
  - warmup
# By default app engine will run npm start if entrypoint not defined
# entrypoint: npm start
